---
sudo: required
language: python
all_branches: true
dist: xenial
python:
  - 3.7
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule python-vagrant
script:
  - cd roles/ansible-role-nginx
  - pwd
  -  molecule lint
  # - molecule lint
  # - molecule destroy
  # - molecule dependency
  # - molecule syntax
  # - molecule converge
  # - travis_wait 20 molecule idempotence
  # - molecule side-effect
  # - molecule verify
  # - molecule destroy
...
