---
- name: Clone repo
  git:
    repo: https://github.com/express42/reddit.git
        # не забудьте подставить своего user
    dest: /home/ubuntu/reddit
    version: microservices
    force: true

- name: apt install dependencies
  apt:
    name: ['python3', 'python3-dev', 'python3-pip', 'python-setuptools']
    state: present
    update_cache: yes

- name: requirements install with pip3
  pip:
    requirements: /home/ubuntu/reddit/post-py/requirements.txt
    executable: /usr/bin/pip3

- name: Add reddit_config
  template:
    src: post_config.j2
    dest: /home/ubuntu/reddit/post-py/post_config

- name: Add unit file for post
  template:
        # Подставляем свой сервис
    src: post.service.j2
    dest: /etc/systemd/system/post.service
  notify: reload post

- name: Start service and enabled at boot
  systemd:
    state: started
    name: post
    enabled: true
    daemon_reload: true
...
